spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=hotel_reservation_db;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

open:
  api:
    title: API Document
    version: v1.0.0
    description: API Service for Hotel Management System
    serverUrl: http://localhost:8080
    serverName: Server Test
